version: '3'

networks:
  default:

services:
  db:
    container_name: ${CONTAINER_NAME}_db
    image: ${IMAGE_NAME}_db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./docker/data/mysql/:/var/lib/mysql
    networks:
      - default
    tty: true

  php:
    container_name: ${CONTAINER_NAME}_php
    image: ${IMAGE_NAME}_php
    build:
      context: .
      dockerfile: docker/app/php/Dockerfile
      args:
        DEBUG_IP: $DEBUG_IP
    env_file:
      - .env
    ports:
      - ${WEB_PORT}:8000
    volumes:
      - ./:/var/www:cached
    depends_on:
      - db
    networks:
      - default
    tty: true
