version: "3"

services:
  db:
    container_name: ${CONTAINER_NAME}_db
    image: ${IMAGE_NAME}_db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    env_file:
      - .env
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./docker/data/mysql/:/var/lib/mysql

  php:
    container_name: ${CONTAINER_NAME}_php
    image: ${IMAGE_NAME}_php
    build:
      context: .
      dockerfile: docker/app/php/Dockerfile
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - ./:/var/www
    tty: true
    depends_on:
      - db
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"

  nginx:
    container_name: ${CONTAINER_NAME}_nginx
    image: ${IMAGE_NAME}_nginx
    build:
      context: .
      dockerfile: docker/app/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./docker/logs/nginx/:/var/log/nginx
      - ./:/var/www
    depends_on:
      - php
    tty: true
