fos_rest:
  routing_loader:
    default_format: json
  body_listener: true
  view:
    view_response_listener: true
  serializer:
    serialize_null: true
  body_converter:
    enabled: true
    validate: true
